### PR TITLE
Implement global shortcuts default value in SwiftUI Mode

### PR DESCRIPTION
**Pull request by CanglongCl**

### CODE REVIEW

**Review by tisfeng — APPROVED** [review]
Looks good.

**Comment by AkaShark** [comment]
https://github.com/tisfeng/Easydict/assets/26460192/c24fef7e-a35f-43da-bbdf-b3a5a94aa637

**Comment by CanglongCl** [comment]
> CleanShot.2024-02-09.at.20.42.38.mp4

You are right. It is a [old issue](https://github.com/sindresorhus/Defaults/issues/54) in `Defaults`.

I'll revert it.

**Comment by CanglongCl** [comment]
> CleanShot.2024-02-09.at.20.42.38.mp4

BTW in release 2.6.0 it works well. I'm not sure why.

**Comment by tisfeng** [comment]
I opened a new issue to track shortcuts bugs https://github.com/tisfeng/Easydict/issues/399

**Pull request merged**
