### PR TITLE
fix: model button hover title issue

### PR DESCRIPTION
**Pull request by phlpsong**
#691

### CODE REVIEW

**Review by AkaShark — APPROVED** [review]
LGTM

**Review by AkaShark — DISMISSED** [review]

**Review by Jerry23011 — APPROVED** [review]
LGTM

**Review by AkaShark — APPROVED** [review]

**Comment by tisfeng** [comment]
@phlpsong  This fix PR is fine.

I accidentally found another issue. Currently, if I don't open the settings services page, after I modify the model, it doesn't refresh the UI, which may cause the model name to be displayed incompletely.

I checked the code and found that the timing of the `reloadLLMServicesSubscribers()` method call is not appropriate. The previous subscription method was called during initialization. 

Please check the code.


https://github.com/user-attachments/assets/c071c2bb-72b0-4638-87ec-c7564c572b1c

**Comment by phlpsong** [comment]
OK, I will check this later.

**Comment by phlpsong** [comment]
OK, I will check this later. @tisfeng

**Comment by tisfeng** [comment]
等这问题解决，我们就可以找时间发布一个新版本了。

**Pull request merged**
