### PR TITLE
pref: remove main storyboard & EasydictHelper

### PR DESCRIPTION
**Pull request by AkaShark**
closed https://github.com/tisfeng/Easydict/issues/553#issuecomment-2110588570

### CODE REVIEW

**Comment by AkaShark** [comment]
CleanShot 2024-06-03 at 22 04 43@2x

I don't know what `EastdictHelper` is for our project, can I delete it, and delete the entire target as well

**Comment by Jerry23011** [comment]
> I don't know what EastdictHelper is for our project

I think it's for launch at login?

**Comment by AkaShark** [comment]
> > I don't know what EastdictHelper is for our project
> 
> I think it's for launch at login?

I am not sure, but I have not encountered some of it in the build settings. I do not have much experience in developing for Mac OS.

**Comment by Jerry23011** [comment]
Not sure either, I think that's what's it's saying in AppDelegate? https://github.com/tisfeng/Easydict/blob/381033d4d27cf95a398ee1c608e33137a9003090/EasydictHelper/AppDelegate.m

**Comment by tisfeng** [comment]
The code related to `EastdictHelper` can now be deleted.

`EastdictHelper` was initially intended to enable the application to start on boot, but users reported that it was ineffective, as seen in this issue: https://github.com/tisfeng/Easydict/issues/64. 

I attempted to use `SMAppService`, but it didn't work out, so I ultimately  used AppleScript to implement it.

https://github.com/tisfeng/Easydict/blob/381033d4d27cf95a398ee1c608e33137a9003090/Easydict/objc/Configuration/EZConfiguration.m#L523

**Comment by AkaShark** [comment]
> SMAppService

OK I will remove the `EasydictHelper`,  I found the commit you said https://github.com/tisfeng/Easydict/commit/f49652f592d33d47a79f7a405e86e9d0aa53be58

**Review by tisfeng — APPROVED** [review]
Looks good.

**Pull request merged**
