### PR TITLE
fix: alert text show up to 1000

### PR DESCRIPTION
**Pull request by tisfeng**
Fix https://github.com/tisfeng/Easydict/issues/742

### CODE REVIEW

**Comment by tisfeng** [comment]
I tried adding ScrollView and limiting the number of frame and lines of Text, but nothing worked.

**Comment by Jerry23011** [comment]
GPT says alert's message view doens't have native support for scroll view, a workaround would be to use `.sheet` to define a custom view. 

https://github.com/user-attachments/assets/ea8c3c90-dd37-4c55-98d0-2b4126801d86

**Comment by tisfeng** [comment]
I see, because [alert](https://developer.apple.com/documentation/swiftui/view/alert(_:ispresented:presenting:actions:message:)-8584l) can only display text-based information 

> On iOS, tvOS, and watchOS, alerts only support controls with labels that are [Text](https://developer.apple.com/documentation/swiftui/text). Passing any other type of view results in the content being omitted.
>
> Only unstyled text is supported for the message.

It's true that a sheet can use a ScrollView, but the alert style is more appropriate here, and  I don't want to spend the effort to modify the sheet into the alert style, it's too tiring.

There are only a few cases where an alert would cause an exception, if there is no better solution, let's simply truncate the text.

**Comment by Jerry23011** [comment]
> It's true that a sheet can use a ScrollView, but the alert style is more appropriate here, and I don't want to spend the effort to modify the sheet into the alert style, it's too tiring.
>
> There are only a few cases where an alert would cause an exception, if there is no better solution, let's simply truncate the text.

True true, let's keep it alert.

**Review by Jerry23011 — APPROVED** [review]

**Pull request merged**
