### PR TITLE
fix: disable app list lag issue

### PR DESCRIPTION
**Pull request by phlpsong**
`List` item views may refresh after selection changes. This change will prevent content refresh after each selection.

After select too many apps in the list, you may experience significant lag behaviors.

### CODE REVIEW

**Comment by phlpsong** [comment]
@CanglongCl This will revert some changes in #340, please kindly check it. Any questions or suggestions, please let me know.

**Comment by tisfeng** [comment]
I tested this code, it doesn't fix on my mac.

**Comment by phlpsong** [comment]
> I tested this code, it doesn't fix on my mac.

To clarify, this is not a fix for #346. 

You could reproduce this issue by:
1. Click `+` to open app importer
2. Select some apps, maybe 10 above
3. Switch the tab or select the apps 

you may experience the list lag sometimes

**Comment by tisfeng** [comment]
Sorry, I misunderstood.

**Comment by phlpsong** [comment]
> I actually tried the previous workaround [#346 (comment)](https://github.com/tisfeng/Easydict/issues/346#issuecomment-1901983231) in SwiftUI and it worked, although it's not elegant.
> 
> If possible, you can try to find out the specific reason.

Sure, I will try.

**Review by CanglongCl — APPROVED** [review]

**Review by Jerry23011 — APPROVED** [review]

**Review by tisfeng — APPROVED** [review]

**Pull request merged**
