### PR TITLE
Service enable not work well issue

### PR DESCRIPTION
**Pull request by phlpsong**
#536 

Not sure if this issue is caused by the translation/sentence/dictionary option being disabled, you could try this and give me feedback if this issue still exists.

[screen-capture.webm](https://github.com/tisfeng/Easydict/assets/103433299/55edc690-e830-4050-9646-b7db2ed02894)

### CODE REVIEW

**Comment by Jerry23011** [comment]
I'm able to reproduce the issue on release v2.7.1, but the issue no longer appears on this PR.

I'm not sure if this PR caused a new issue of not being able to toogle on the service for several attempts. It seems to appear only on Built-in AI Translation service


https://github.com/tisfeng/Easydict/assets/89069957/d8dc1341-021c-4c19-960c-919897058a9a

**Comment by phlpsong** [comment]
Appreciate for your feedback. 

Could u check if you disable all options in configuration? 

Enable state will not changed if user disable all the options like translation/sentence/dictionary. So I think it's an expected behavior no options enabled.

**Comment by Jerry23011** [comment]
> Could u check if you disable all options in configuration?

Yes indeed, now it works, thanks

**Review by Jerry23011 — DISMISSED** [review]

**Review by AkaShark — APPROVED** [review]

**Comment by tisfeng** [comment]
I thought about it, and I feel that the enabled query types should not affect whether the service is enabled or not, as it may confuse users, and intuitively they should be independent.

So I changed the code 05ed2786 , please let me know what you think.

**Comment by Jerry23011** [comment]
This is more convenient for new users, but would it be better if Translation query is toggled on the same time when the service is toggled?

Sample use case:
1. The service Built-in Translation is disabled, and all three query type are disabled
2. Toggle on Built-in Translation
3. Go into Built-in Translation and find that all three query types are disabled.

In this case, would it be nice if translation query is toggled on at the same time so that users know that it's the default query type?

**Comment by tisfeng** [comment]
I think it would be better to keep the service enabled or not independent of the query type. Whether the service is enabled determines whether it is displayed in the query window, and the query type determines the query action.

Though your suggestion is good, it associates the enabling of the service with the query type, which could cause some cognitive complexity. 

I prefer to let users decide to turn on or off these query types, giving users freedom.

I'd like to try to keep it simple, keep the application simple to configure and use, and easy to understand.

**Comment by phlpsong** [comment]
Looks good, it's better and more simple and will be less confusing for the user.

**Comment by Jerry23011** [comment]
Yes that's true, LGTM

**Review by Jerry23011 — APPROVED** [review]

**Pull request merged**
