### PR TITLE
perf: use CGRequestScreenCaptureAccess to get screen permission

### PR DESCRIPTION
**Pull request by tisfeng**
And  show alert if has no screen access.

Close https://github.com/tisfeng/Easydict/issues/587

### CODE REVIEW

**Review by Jerry23011 — DISMISSED** [review]
Though macOS 15 b1 still shows a popup, the API changes works well itself

**Review by phlpsong — APPROVED** [review]

**Review by AkaShark — APPROVED** [review]

**Comment by tisfeng** [comment]
> Though macOS 15 b1 still shows a popup, the API changes works well itself

There was an issue with the previous code. We should use `CGPreflightScreenCaptureAccess` to check for authorization status. If permission is not granted, use `CGRequestScreenCaptureAccess` to request access ba9b26c9 . 

Please test again.

**Comment by tisfeng** [comment]
There was an issue with the previous code. We should use `CGPreflightScreenCaptureAccess` to check for authorization status. If permission is not granted, use `CGRequestScreenCaptureAccess` to request access ba9b26c9 . 

@Jerry23011  Please test again.

**Comment by Jerry23011** [comment]
Now we have a new-looking popup requesting permission when the app is first installed. However, the warning popup still persists after Mac restart.

**Comment by tisfeng** [comment]
It's strange, this PR code seems fine, I think we can merge it first.

There's no further information on the macOS 15 beta yet, we'll keep an eye on it.

**Pull request merged**
