### PR TITLE
Refactor Launch At Login with launchatlogin-modern

### LINKED ISSUE #646: "Launch at login" doesn't work
### Please confirm the following:

- [x] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

When I activate "_launch at login_" it doesn't really add it to the login items or start it when I reboot the system.

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

Read problem description

### Screenshot

Captura de pantalla 2024-08-16 a las 10 07 11

### Runtime log

[com.izual.Easydict 2024-08-16--07-54-56-460.log](https://github.com/user-attachments/files/16634677/com.izual.Easydict.2024-08-16--07-54-56-460.log)

### Expected result

It should add _easydict_ to the login items on macOS.

### Proposed solution (optional)

_No response_

### Device type and OS version

Apple M2, macOS 14.5

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR to fix this issue

### PR DESCRIPTION
**Pull request by Jerry23011**
Closes #646

### CODE REVIEW

**Comment by Jerry23011** [comment]
I found that the `logSettings` func doesn't produce any output anywhere? I also tried other Setting items that calls the func but I don't seem to observe any log outputs.

**Comment by tisfeng** [comment]
下次如果打算要 PR，记得先把 issue 分配自己，这样避免其他人同时关注该 issue。

**Comment by tisfeng** [comment]
> I found that the `logSettings` func doesn't produce any output anywhere? I also tried other Setting items that calls the func but I don't seem to observe any log outputs.我发现 `logSettings` func 在任何地方都没有产生任何输出？我还尝试了其他调用 func 的设置项，但我似乎没有观察到任何日志输出。

The `logSettings` calls the `EZLog` method, which is not a local log, but a remote statistical log from [App Center](https://appcenter.ms/).

```swift
fileprivate func logSettings(_ parameters: [String: Any]) {
        EZLog.logEvent(withName: "settings", parameters: parameters)
    }
```

**Review by tisfeng — APPROVED** [review]
Good job!

**Pull request merged**
