### PR TITLE
Official Web Site

### PR DESCRIPTION
**Pull request by yangg**
#356 

vitepress is a good choice, as it can
1. save most of the design and styles
2. suitable for writing help documents.
3. deploy to netlify, without need a server & domain. And acceptable speed in Mainland.
4. easy for Internationalization

I created one: https://easydict.netlify.app/

## Update:
All the document can be written in markdown format. like you write the readme.md
If you think it's ok, I will fill in some existing documents in the next few days, set up the basic structure, and then others can directly edit the markup

I've added
- [x] Internationalization folder structure
- [x] Installation doc
- [x] Migrate the "how tos" docs in old `docs` dir

### CODE REVIEW

**Comment by tisfeng** [comment]
@yangg  Looks great,  is the current https://easydict.netlify.app generated from this PR's documentation?

Can I now deploy this docs directly to other platforms?

**Comment by yangg** [comment]
> @yangg Looks great, is the current https://easydict.netlify.app generated from this PR's documentation?
> 
> Can I now deploy this docs directly to other platforms?

@tisfeng Yes, it just works in vercel without any extra config. here is a demo  https://easydict-demo.vercel.app/

**Comment by CanglongCl** [comment]
Looks great. But should we use another repo instead of put it here?

**Comment by phlpsong** [comment]
> Looks great. But should we use another repo instead of put it here?

Agree, using a separate repo is better.

**Comment by tisfeng** [comment]
@yangg  That's great, thank you very much!

We can try to complete the missing docs in https://easydict.netlify.app

**Comment by AkaShark** [comment]
> Looks great. But should we use another repo instead of put it here?

+1

**Comment by AkaShark** [comment]
Other than that we will merge in  main ?
CleanShot 2024-02-02 at 11 28 59@2x

**Comment by yangg** [comment]
> Looks great. But should we use another repo instead of put it here?

https://github.com/yangg/easydictdoc is ready.

> Other than that we will merge in main ? CleanShot 2024-02-02 at 11 28 59@2x

@AkaShark @CanglongCl  https://github.com/yangg/easydictdoc is ready for days before this pull request.

**Comment by tisfeng** [comment]
Ok, I will create a new repo for docs later, let's keep this repo clean.

**Comment by tisfeng** [comment]
Hi, I created a new repo [easydict-docs](https://github.com/tisfeng/easydict-docs), which imported from [easydictdoc](https://github.com/yangg/easydictdoc), we can continue to improve the docs on this repo.

**Comment by tisfeng** [comment]
Hi @yangg 

I just deployed [easydict-docs](https://github.com/tisfeng/easydict-docs) in Vercel https://easydict-docs.vercel.app/ , but it seems to have some problems. Can you help me take a look?

image

**Comment by yangg** [comment]
@tisfeng 

You may need to remove "docs" from vercel settings,
or move all the files except package.json into docs directory
image

**Comment by tisfeng** [comment]
ok, it worked, thanks.

**Pull request closed without merging**
