### PR TITLE
fix: port config subtitle text wrap issue

### PR DESCRIPTION
**Pull request by phlpsong**
Before:
Screenshot 2024-10-12 at 11 39 46

After:

Screenshot 2024-10-12 at 11 40 54

### CODE REVIEW

**Comment by Jerry23011** [comment]
I have no problem building it on my end, but I'm wondering why it couldn't pass the CI?

**Comment by phlpsong** [comment]
> I have no problem building it on my end, but I'm wondering why it couldn't pass the CI?

I guess CI use the different version of Xcode, it's fixed in https://github.com/tisfeng/Easydict/pull/693/commits/d4c81f6193bc260de690c41e745de190ec7cadf8.

**Comment by Jerry23011** [comment]
> > I have no problem building it on my end, but I'm wondering why it couldn't pass the CI?
> 
> I guess CI use the different version of Xcode, it's fixed in [d4c81f6](https://github.com/tisfeng/Easydict/commit/d4c81f6193bc260de690c41e745de190ec7cadf8).

I see. Then LGTM

**Review by Jerry23011 — APPROVED** [review]

**Comment by tisfeng** [comment]
Good!

**Comment by tisfeng** [comment]
我更新了 CI image，改成了 macos-15 ed044585，现在 Swift Package 可以使用 version 3 了 😃

**Pull request merged**
